name: Build Minescript (Fabric Only)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NO_MINESCRIPT_FORGE_BUILD: "1"
      NO_MINESCRIPT_NEOFORGE_BUILD: "1"

    steps:
      - name: Checkout Minescript
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Clone Pyjinn
        run: git clone https://github.com/maxuser0/pyjinn.git

      - name: Build & Publish Pyjinn
        working-directory: pyjinn
        run: |
          chmod +x gradlew
          ./gradlew interpreter:publishToMavenLocal
      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Fabric Mod
        run: ./gradlew :fabric:build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: minescript-fabric
          path: fabric/build/libs/*.jar
